theme: jekyll-theme-cayman
url: "https://branding.mindtwo.de"
title: Agency Branding Guide
description: This site contains a set of guidelines we use to bring our brand mindtwo to a good end. We decided to document our branding because consistency is one of the most valuable traits.
